// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkKA1eQpJv-SE_ZKYyDd3DsYW-bcVvrek',
    appId: '1:21368898903:web:9e97288381aa71bae62a12',
    messagingSenderId: '21368898903',
    projectId: 'pawtopia-4d2f4',
    authDomain: 'pawtopia-4d2f4.firebaseapp.com',
    storageBucket: 'pawtopia-4d2f4.firebasestorage.app',
    measurementId: 'G-Z9HY4F6K11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoHIKPykQrmASC8Kg1YEWtrS4wd65Aees',
    appId: '1:21368898903:android:51d97b6c339d8487e62a12',
    messagingSenderId: '21368898903',
    projectId: 'pawtopia-4d2f4',
    storageBucket: 'pawtopia-4d2f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi3QviR-Qhn3W5Az_Nzcj3QJ234N4vkcQ',
    appId: '1:21368898903:ios:1b1fb4ea377737ede62a12',
    messagingSenderId: '21368898903',
    projectId: 'pawtopia-4d2f4',
    storageBucket: 'pawtopia-4d2f4.firebasestorage.app',
    iosBundleId: 'com.example.pawtopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi3QviR-Qhn3W5Az_Nzcj3QJ234N4vkcQ',
    appId: '1:21368898903:ios:1b1fb4ea377737ede62a12',
    messagingSenderId: '21368898903',
    projectId: 'pawtopia-4d2f4',
    storageBucket: 'pawtopia-4d2f4.firebasestorage.app',
    iosBundleId: 'com.example.pawtopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkKA1eQpJv-SE_ZKYyDd3DsYW-bcVvrek',
    appId: '1:21368898903:web:0f47ce201eea0581e62a12',
    messagingSenderId: '21368898903',
    projectId: 'pawtopia-4d2f4',
    authDomain: 'pawtopia-4d2f4.firebaseapp.com',
    storageBucket: 'pawtopia-4d2f4.firebasestorage.app',
    measurementId: 'G-XZJ53YWJNC',
  );
}
